### ISSUE TITLE
Validation rule for test_repeater

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-test-plugin#6]
The validation rule for the fields added by extending `Page` model is maybe a little too much restrictive.
https://github.com/wintercms/wn-test-plugin/blob/4571241c0079d838463e5982d449ab21729d5644/Plugin.php#L198

I was fooled myself during tests.
And in [this issue](https://github.com/Hounddd/wn-blocks-theme/issues/1#issue-903549450) : 

> If I add new blocks - the system show error "**The test repeater field is required.**"

Maybe a warning in the readme?

**Comment by LukeTowers** [comment]
The test plugin should never be installed in production

**Comment by LukeTowers** [comment]
What warning would you add to the readme?

**Comment by damsfx** [comment]
> 
> 
> What warning would you add to the readme?

That the behaviour of the page module is altered by this extension; by adding a required field?  
But as you pointed out, this plugin is for testing purposes only; perhaps we can hope that those who install it will be careful.
